experiment_name: Test_model

models:
  RandomForest:
    class: RandomForestClassifier
    params: {}

  Tree:
    class: DecisionTreeClassifier
    params: { }

  naive:
    class: GaussianNB
    params: {}

test:
  func: cross_validate
  op: mean
  cv: 2
  scoring:
  - r2
  - neg_mean_absolute_error
  - neg_mean_squared_error

save:
  path: /data
  type: mean
  save_func: 
    - save_mlflow
