experiment_name: Test_model

models:
  RandomForest:
    class: RandomForestClassifier
    params:
      max_depth: 20
      n_estimators: 15

  Tree:
    class: DecisionTreeClassifier
    params: { }

  Testes_novos:
    class: RandomForestClassifier
    params:
      max_depth: 10
      n_estimators: 15

  naive:
    class: GaussianNB
    params: {}

test:
  func: cross_validate
  op: mean
  cv: 2
  scoring:
  - r2
  - neg_mean_absolute_error
  - neg_mean_squared_error

save:
  path: /data
  type: mean
  save_func: 
    - save_mlflow
